### ISSUE TITLE
ERROR: badly formed, due to query ending up with strange capitalization

### ISSUE THREAD

**Issue by JesseCrocker** [ConradIrwin/aws-name-server#15]
Running a query over the internet:

```
$ dig @awsdns.gaiagps.com 1.coreoscluster.role.aws.gaiagps.com CNAME                                                                                                                                                              [12:13:00]

; <<>> DiG 9.8.3-P1 <<>> @awsdns.gaiagps.com 1.coreoscluster.role.aws.gaiagps.com CNAME
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4488
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;1.coreoscluster.role.aws.gaiagps.com. IN CNAME

;; AUTHORITY SECTION:
aws.gaiagps.com.    59  IN  SOA awsdns.gaiagps.com. me.cirw.in. 1470679987 86400 7200 86400 60

;; Query time: 141 msec
;; SERVER: 52.2.57.111#53(52.2.57.111)
;; WHEN: Mon Aug  8 12:13:06 2016
;; MSG SIZE  rcvd: 107
```

Error in server log:

```
2016/08/08 18:13:07 CNAME "1.cOrEosCLUStEr.roLe.AWS.gaiAGpS.coM." XXXX:38638 (id=30398)
2016/08/08 18:13:07 ERROR: badly formed: 1.cOrEosCLUStEr.roLe.AWS.gaiAGpS.coM. []string{"cOrEosCLUStEr", "roLe", "AWS", "gaiAGpS", "coM", ""}
```

There are 4 ec2 instances tagged `coreoscluster`

The queries were working fine until recently.

**Comment by ConradIrwin** [comment]
Hey @JesseCrocker,

This is peculiar...  Do you have any idea what's generating those queries or processing them to muddle case?

I didn't consider case when creating ec2-name-server, and as hostnames are officially case insensitive, it may be possible to fix your issues by downcasing the query https://github.com/ConradIrwin/aws-name-server/blob/master/ec2_server.go#L118 — would you be able to checkout the version on the `lowercase-queries` branch and see if this fixes it for you?

P.S. I _love_ the Gaia GPS App — installed it about 2 months ago and have been using it avidly every hike since.

**Comment by JesseCrocker** [comment]
Thanks for the quick fix! I switched to the `lowercase-queries` branch and everything is working again.

As to why the queries are ending up with crazy case, i can't figure that out. They're all lower case leaving my machine, and mixed case when they arrive.

@ConradIrwin Can i give you a free subscription to Gaia Pro(gets you more map sources, and some more features)?
